nvme-cli: fix possible string truncation
The snprintf() statement could require more space than was allocated for
fmt for large firmware revision numbers.

Fixes warning enabled by -fsanitize=undefined:

  nvme-print.c:1685:49: error: ‘%d’ directive output may be truncated
  writing between 1 and 10 bytes into a region of size 3
  [-Werror=format-truncation=]

Change-Id: I1463603e049a82b954b56986cef73e755ac4c4a1
Signed-off-by: Daniel Verkamp <daniel.verkamp@intel.com>